import { cn } from '@promptus/utils';
import { Layout } from '@promptus/ui';

import './global.css';
import { Inter as FontSans } from 'next/font/google';
import { SuperTokensProvider } from '@promptus/feature';

export const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
});

export const metadata = {
  title: 'Welcome to admin-web',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <SuperTokensProvider>
        <body
          className={cn(
            'min-h-screen bg-background font-sans antialiased',
            fontSans.variable
          )}
        >
          <Layout>{children}</Layout>
        </body>
      </SuperTokensProvider>
    </html>
  );
}
