import './global.css';
import { Inter as FontSans } from 'next/font/google';
import { SuperTokensProvider } from '@promptus/web/auth/feature';
import { cn } from '@promptus/web/shared/util';
import { ThemeProvider } from '@promptus/web-shared-ui';

export const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
});

export const metadata = {
  title: 'Welcome to admin-web',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <SuperTokensProvider>
        <body
          className={cn(
            'min-h-screen font-sans antialiased',
            fontSans.variable
          )}
        >
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {children}
          </ThemeProvider>
        </body>
      </SuperTokensProvider>
    </html>
  );
}
